# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shared_histories", type: :request do
  # SharedHistory. As you add validations to SharedHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SharedHistory.create! valid_attributes
      get shared_histories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shared_history = SharedHistory.create! valid_attributes
      get shared_history_url(shared_history)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_shared_history_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      shared_history = SharedHistory.create! valid_attributes
      get edit_shared_history_url(shared_history)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SharedHistory" do
        expect {
          post shared_histories_url, params: { shared_history: valid_attributes }
        }.to change(SharedHistory, :count).by(1)
      end

      it "redirects to the created shared_history" do
        post shared_histories_url, params: { shared_history: valid_attributes }
        expect(response).to redirect_to(shared_history_url(SharedHistory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SharedHistory" do
        expect {
          post shared_histories_url, params: { shared_history: invalid_attributes }
        }.to change(SharedHistory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post shared_histories_url, params: { shared_history: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shared_history" do
        shared_history = SharedHistory.create! valid_attributes
        patch shared_history_url(shared_history), params: { shared_history: new_attributes }
        shared_history.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the shared_history" do
        shared_history = SharedHistory.create! valid_attributes
        patch shared_history_url(shared_history), params: { shared_history: new_attributes }
        shared_history.reload
        expect(response).to redirect_to(shared_history_url(shared_history))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shared_history = SharedHistory.create! valid_attributes
        patch shared_history_url(shared_history), params: { shared_history: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shared_history" do
      shared_history = SharedHistory.create! valid_attributes
      expect {
        delete shared_history_url(shared_history)
      }.to change(SharedHistory, :count).by(-1)
    end

    it "redirects to the shared_histories list" do
      shared_history = SharedHistory.create! valid_attributes
      delete shared_history_url(shared_history)
      expect(response).to redirect_to(shared_histories_url)
    end
  end
end
